# Generated by Django 4.2.1 on 2023-06-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecategory',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images'),
        ),
    ]
