# Generated by Django 4.2.1 on 2023-06-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_placecategory_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='placecategory',
            name='category_slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
