# Generated by Django 4.2.1 on 2023-06-06 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0003_placecategory_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='followed_list',
            field=models.ManyToManyField(blank=True, related_name='place_followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
