# Generated by Django 4.2.1 on 2023-07-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_interest_profile_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pinterest',
            new_name='tiktok',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
    ]
